### ISSUE TITLE
Canvas not sized correctly

### ISSUE THREAD

**Issue by Phifejac** [tengbao/vanta#46]
After your most recent push this morning, my birds canvas element was no longer sizing correctly. Instead of filling the screen as it usually does, it was only a thin strip at the top of the screen. The width is still correct but the height is only about 100 pixels. I added the new snippet of code that was posted on the demo example of the birds but this still did not remedy the issue.

Please let me know if there is something else that I need to change. This is affecting my production build so I would like to remedy it as quickly as possible.

**Comment by tengbao** [comment]
@Phifejac You'll need to manually set the size of the container element (the `el` param) to 100% width and 100% height. (You can do that however you'd like, using CSS or JS.) The logic is now that the canvas element automatically fills the size of the container `el`. If your container is too small, the canvas will be set to a minimum width/height (200px). Check the new readme for more info about the `el` param.

Also, I recommend against hotlinking since new versions can break production code.

**Comment by Phifejac** [comment]
Thank you for your quick response! That makes sense.
