### ISSUE TITLE
Unequal rendering depending on Operating System

### ISSUE THREAD

**Issue by b4D8** [tengbao/vanta#67]
Hi! 
I'm using Vanta Fog and noticed that rendering is very unequal depending mostly on the operating system.
I found that fog looks nice on UNIX-based systems (tested on Debian, OSX and Android) but "edgy" on Windows (contours are sharp and therefore not much foggy).
Speed also is inconsistent (5.00 is slow on UNIX and fast on Windows).
I tested with several devices and browsers and that unattended behavior is quite consistent.
Does anyone relates to this?

Thanks for your help!

**Comment by michaeljblum** [comment]
Just wanted to chime in - reporting the same phenomenon, although reversed: Fog has sharp edges on Mac, but is smoothed out and properly "blurry" on Windows. Anyone encounter a fix to this sharp-edged Fog issue?

**Comment by MaSchVam** [comment]
Hi @b4D8 and @michaeljblum, I am currently creating a site where I use this effect as well - and discovered this too. 

From my tests, it actually has nothing to do with OS - the culprit here seems to be Retina screens (high DPI). I also noticed that the "Trunk", "Clouds" and "Topology" effects are broken on these types of screens as well.

For the time being, the Fog effect is somewhat salvageable by serving conditional zoom and blur levels on the initialization of the effect - [here](https://www.kirupa.com/html5/detecting_retina_high_dpi.htm) is a guide on how to detect high DPI screens in JavaScript. 

The other effects, especially the "Trunk" effect, unfortunately are hard to use on these screens. @tengbao can you confirm?

**Comment by b4D8** [comment]
Hi!  Thanks for your feedback. You're right with th OS. Thats weird though, I tested on several devices high DPI and normal screens...and could find a clear pattern for this. I came to beleive thats related to the graphic card.

**Comment by MaSchVam** [comment]
Okay, actually I went and did some deep digging on this - and think I may have found an actual fix for Retina screens, by "MasatoMakino" in [this thread](https://github.com/patriciogonzalezvivo/thebookofshaders/issues/293).

We can essentially go ahead and change the float at the very bottom of the Vanta Fog file, from:

```
float random (in vec2 _st) {
    return fract(sin(dot(_st.xy,
                         vec2(12.9898,78.233)))*
        43758.5453123);
}
```

to:

```
float random (in vec2 _st) {
    return fract(sin(dot(_st.xy,
                         vec2(0.129898,0.78233)))*
        437.585453123);
}
```

And it should produce a visually similar result across all screens and hardware. It looks like a decimal point is getting lost, because the number passed to the `fract` function is too large.
